title: Louis Kim Le Vu # your name (or website title) here
logo: "/images/kim-photo.png?raw=true" # your photo (or logo) here
description: >- # your text below (remove <br> elements if you don't need line breaks)
  #<a href="https://www.linkedin.com/in/louiskimlevu/">My Linkedin</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

description: > # your text below (remove <br> elements if you don't need line breaks)
  Tech stack:
  <br><br>
  Web Framework: 
  <br>
  Backend: Python/Flask
  <br>
  Frontend: HTML
  
  <br><br>
  Cloud: 
  <br>
  AWS
  <br>
  GCP
  
  <br><br>
  Deployment: 
  <br>
  Containers(Docker, Kubernetes)
  <br>
  AppEngine (PAAS)    
  
  <br><br>
  Machine Learning:
  <br>
    - Supervised: 
      <br>
      Regression: Linear
      Classification: Decision Tree, Random Forest, KNN

