title: Louis Kim Le Vu # your name (or website title) here
logo: "/images/kim-photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
    <a href="https://www.linkedin.com/in/louiskimlevu/">linkedin.com/in/louiskimlevu/</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
